name: Notify Main Repository

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: Sub_Runner  # This label added to the "HP-ZBPG8-TEST2" machine for TWI_ORG_RUNNER runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.YOUSSEF_RUNNER }}

      - name: Trigger update-submodules workflow
        run: |
            $headers = @{
            "Accept" = "application/vnd.github.v3+json"
            "Authorization" = "token ${{ secrets.YOUSSEF_RUNNER }}"
            }

            $body = @{
              "event_type" = "Auto_Build"
            } | ConvertTo-Json -Compress  # Convert the hashtable to a JSON object

            # Send the POST request to GitHub API to trigger the workflow
            Invoke-WebRequest -Uri "https://api.github.com/repos/YoussefHeshamSalah/test/dispatches" `
                              -Method Post `
                              -Headers $headers `
                              -Body $body `
                              -ContentType "application/json"
